package fitness_tracker.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;
import java.time.LocalDateTime;
import java.util.List;

/**
 * This file represents a piece of feedback or fitness advice
 * generated by the application for a user.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Recommendation {

    /** A unique, random ID string given to this advice record */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** Links this advice to the specific User who receives it */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id",nullable = false,foreignKey = @ForeignKey(name = "fk_recommendation_user"))
    @JsonIgnore
    private User user;

    /** Links this advice to the specific Activity workout session that triggered it */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "activity_id",nullable = false,foreignKey = @ForeignKey(name = "fk_recommendation_activity"))
    @JsonIgnore
    private Activity activity;

    /** The category type of the advice given */
    private String type;

    /** The main feedback message text (allows up to 2000 letters/symbols) */
    @Column(length = 2000)
    private String recommendation;

    /** A list of specific things the user can improve on next time */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private List<String> improvements;

    /** A list of action steps or helpful ideas for the user */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private List<String> suggestions;

    /** A list of safety instructions to help the user avoid injuries */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private List<String> safety;

    /** Automatically saves when this advice was first given */
    @CreationTimestamp
    private LocalDateTime createdAt;

    /** Automatically updates if the advice message is modified */
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}