spring.application.name=fitness-tracker

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_demo
spring.datasource.username=postgres
spring.datasource.password=nabin99

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console (optional but useful)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSON handling (important for your Map field)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true